"""Unit tests for the per-turn TZ header (issue #51).

The header is generated by a pure function so the test surface is
small and self-contained. We exercise the four cases that have bitten
prior agent generations: a non-UTC user, a DST-edge timestamp, a
half-hour offset zone, and the UTC base case.
"""

from __future__ import annotations

from datetime import UTC, datetime

import pytest
from eidan_backend.turn_header import (
    EIDAN_BASE_IDENTITY,
    build_turn_header,
    compose_system_prompt,
)


def _utc(year, month, day, hour=0, minute=0) -> datetime:
    return datetime(year, month, day, hour, minute, tzinfo=UTC)


def test_header_renders_user_local_clock_in_london() -> None:
    # 2026-05-14 23:13 in Europe/London (BST = UTC+1) is 22:13 UTC.
    header = build_turn_header(
        sent_at_utc=_utc(2026, 5, 14, 22, 13),
        user_tz="Europe/London",
        now_utc=_utc(2026, 5, 14, 22, 14),
    )
    assert "2026-05-14T22:13:00Z" in header
    assert "2026-05-14 23:13 in Europe/London" in header
    assert "UTC now is 2026-05-14T22:14:00Z" in header


def test_header_handles_dst_spring_forward_in_us_pacific() -> None:
    # 2026-03-08 10:00 UTC is 2026-03-08 03:00 in America/Los_Angeles
    # (the day clocks spring forward from 02:00 PST → 03:00 PDT).
    header = build_turn_header(
        sent_at_utc=_utc(2026, 3, 8, 10, 0),
        user_tz="America/Los_Angeles",
        now_utc=_utc(2026, 3, 8, 10, 1),
    )
    assert "2026-03-08 03:00 in America/Los_Angeles" in header


def test_header_handles_half_hour_offset_in_kolkata() -> None:
    # 2026-05-14 22:13 UTC is 2026-05-15 03:43 in Asia/Kolkata (UTC+5:30).
    header = build_turn_header(
        sent_at_utc=_utc(2026, 5, 14, 22, 13),
        user_tz="Asia/Kolkata",
        now_utc=_utc(2026, 5, 14, 22, 13),
    )
    assert "2026-05-15 03:43 in Asia/Kolkata" in header


def test_header_falls_back_to_utc_when_zone_unknown() -> None:
    header = build_turn_header(
        sent_at_utc=_utc(2026, 5, 14, 22, 13),
        user_tz="Atlantis/Sunken",  # not a real IANA zone
        now_utc=_utc(2026, 5, 14, 22, 13),
    )
    assert "in UTC" in header
    assert "Atlantis/Sunken" not in header


def test_header_rejects_naive_datetime() -> None:
    with pytest.raises(ValueError, match="timezone-aware UTC"):
        build_turn_header(
            sent_at_utc=datetime(2026, 5, 14, 22, 13),  # naive!
            user_tz="Europe/London",
        )


def test_header_accepts_non_utc_aware_datetime_and_converts() -> None:
    # A surface that mistakenly hands over a London-local but
    # timezone-aware datetime still works — it gets converted to UTC.
    from zoneinfo import ZoneInfo

    london = datetime(2026, 5, 14, 23, 13, tzinfo=ZoneInfo("Europe/London"))
    header = build_turn_header(
        sent_at_utc=london,
        user_tz="Europe/London",
        now_utc=_utc(2026, 5, 14, 22, 14),
    )
    # The render is consistent: 23:13 local, 22:13 UTC.
    assert "2026-05-14T22:13:00Z" in header
    assert "2026-05-14 23:13 in Europe/London" in header


def test_compose_system_prompt_keeps_header_first() -> None:
    header = "[turn header]\nfoo\n[/turn header]\n"
    composed = compose_system_prompt(
        header=header,
        user_prompt="You are a friendly assistant.",
    )
    assert composed.startswith(header)
    assert composed.endswith("You are a friendly assistant.")


def test_compose_system_prompt_stands_alone_without_user_prompt() -> None:
    header = "[turn header]\nfoo\n[/turn header]\n"
    composed = compose_system_prompt(header=header, user_prompt=None)
    # The header still comes through whole; trailing newline normalised.
    assert composed.rstrip() == header.rstrip()


def test_compose_system_prompt_inserts_identity_between_header_and_prompt() -> None:
    header = "[turn header]\nfoo\n[/turn header]\n"
    composed = compose_system_prompt(
        header=header,
        identity=EIDAN_BASE_IDENTITY,
        user_prompt="You are a friendly assistant.",
    )
    assert composed.startswith(header)
    assert composed.endswith("You are a friendly assistant.")
    assert EIDAN_BASE_IDENTITY in composed
    # Identity must sit between the header and the user_prompt, not after.
    assert composed.index(EIDAN_BASE_IDENTITY) > composed.index(header)
    assert composed.index(EIDAN_BASE_IDENTITY) < composed.index(
        "You are a friendly assistant."
    )


def test_compose_system_prompt_identity_stands_alone_without_user_prompt() -> None:
    header = "[turn header]\nfoo\n[/turn header]\n"
    composed = compose_system_prompt(
        header=header, identity=EIDAN_BASE_IDENTITY, user_prompt=None
    )
    assert composed.startswith(header)
    assert EIDAN_BASE_IDENTITY.rstrip() in composed
    assert composed.endswith("\n")


def test_eidan_base_identity_names_eidan_and_disclaims_other_brands() -> None:
    # Load-bearing assertion: the baseline must mention Eidan and explicitly
    # disclaim the underlying model brand. If someone edits the prompt to
    # remove either, this test forces them to also update this assertion —
    # a deliberate speed bump for the LLM-identity surface.
    assert "Eidan" in EIDAN_BASE_IDENTITY
    assert "Claude" in EIDAN_BASE_IDENTITY
    assert "ChatGPT" in EIDAN_BASE_IDENTITY
