// SPDX-License-Identifier: AGPL-3.0-or-later
// AUTO-GENERATED by `eidan deploy` build-context assembly (#284).
// Do not edit — regenerated from each plugin's frontend manifest.
//
// This committed copy is the EMPTY base case (no plugin frontends), so a
// plain `pnpm dev` / `pnpm build` from the core checkout type-checks and
// runs without an assembly step. `eidan deploy` overwrites it (and the
// sibling `apps/web/src/plugins/<name>/` dirs) with the operator's
// assembled plugin frontends, which are gitignored.
import type { ComponentType } from "react";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type PluginLoad = () => Promise<{ default: ComponentType<any> }>;
export type PluginRoute = { plugin: string; path: string; load: PluginLoad };
export type PluginSlotEntry = { plugin: string; slot: string; load: PluginLoad };

export const pluginRoutes: PluginRoute[] = [];

export const pluginSlots: PluginSlotEntry[] = [];
