// SPDX-License-Identifier: AGPL-3.0-or-later
// AUTO-GENERATED by `eidan deploy` build-context assembly (#284).
// Do not edit — regenerated from each plugin's frontend manifest.
//
// This committed copy is the EMPTY base case (no plugin frontends), so a
// plain `pnpm dev` / `pnpm build` from the core checkout type-checks and
// runs without an assembly step. In deployed instances, `eidan deploy`
// overwrites this (and the sibling `apps/web/src/plugins/<name>/` dirs)
// with the operator's assembled plugin frontends, which are gitignored.
// Local development without `eidan deploy` will have no plugins loaded,
// but the type-check, dev server, and build all succeed standalone.
import type { ComponentType } from "react";
import type { NavContribution } from "@/lib/shell/nav";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type PluginLoad = () => Promise<{ default: ComponentType<any> }>;
export type PluginRoute = { plugin: string; path: string; load: PluginLoad };
export type PluginSlotEntry = { plugin: string; slot: string; load: PluginLoad };

export const pluginRoutes: PluginRoute[] = [];

export const pluginSlots: PluginSlotEntry[] = [];

// Nav sections contributed by installed plugins (design §4 "dynamic-by-bundle").
// Empty in the base build; assembly appends one entry per plugin frontend that
// declares a nav contribution, so its sections appear in the rail + bottom bar.
export const pluginNav: NavContribution[] = [];
