// SPDX-License-Identifier: AGPL-3.0-or-later
// AUTO-GENERATED by eidan deploy assembly (#284). Do not edit — regenerated from each plugin's eidan.frontend manifest.
import type { ComponentType } from "react";
import type { NavContribution } from "@/lib/shell/nav";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type PluginLoad = () => Promise<{ default: ComponentType<any> }>;
export type PluginRoute = { plugin: string; path: string; load: PluginLoad };
export type PluginSlotEntry = { plugin: string; slot: string; load: PluginLoad };

export const pluginRoutes: PluginRoute[] = [
  { plugin: "imap", path: "/", load: () => import("@/plugins/imap/Accounts") },
  { plugin: "ical", path: "/", load: () => import("@/plugins/ical/Calendars") },
  { plugin: "google", path: "/", load: () => import("@/plugins/google/Connections") },
  { plugin: "google", path: "/callback", load: () => import("@/plugins/google/Callback") }
];

export const pluginSlots: PluginSlotEntry[] = [
];

export const pluginNav: NavContribution[] = [
  {"bundle":"imap","group":"Integrations","sections":[{"id":"mail","label":"Mail","icon":"mail","href":"/p/imap","mobileHome":5}]},
  {"bundle":"ical","group":"Integrations","sections":[{"id":"calendars","label":"Calendars","icon":"calendar","href":"/p/ical","mobileHome":4}]},
  {"bundle":"google","group":"Integrations","sections":[{"id":"gmail","label":"Google","icon":"mail","href":"/p/google","mobileHome":5}]}
];
