"""Per-turn system-prompt header — timezone discipline (issue #51).

Every provider call within a turn (scope classifier, sizer, intent
classifier, primary, critic) is prefixed with the same deterministic
header that pins three clocks:

- when the surface received the user's input (UTC),
- the user's local time in their IANA time zone,
- UTC right now (the loop's wall clock).

The header is generated by a pure function so it stays trivially
testable across DST boundaries, half-hour offsets, and the UTC base
case. It is *not* produced by a classifier — the loop is the
authority on what time it is, the model is not.

Per docs/005 §5.2 ('lean base context') the header is short — a few
lines — and adds no jargon. The model parses it because it is
unambiguous, not because it is long.
"""

from __future__ import annotations

from datetime import UTC, datetime
from zoneinfo import ZoneInfo


def build_turn_header(
    *,
    sent_at_utc: datetime,
    user_tz: str,
    now_utc: datetime | None = None,
) -> str:
    """Render the per-turn TZ header.

    Parameters
    ----------
    sent_at_utc:
        When the surface received the user's input. MUST be timezone-
        aware UTC; the function asserts this so a naive datetime can't
        silently leak through.
    user_tz:
        IANA zone name. Falls back to `UTC` if the zone is unknown —
        better to render a slightly less helpful header than to refuse
        the turn.
    now_utc:
        Override for the loop's wall clock. Defaults to
        ``datetime.now(timezone.utc)``. Injected in tests.

    Returns
    -------
    A string suitable for prepending verbatim to every provider call's
    system prompt for this turn. Includes a trailing newline so the
    caller can concatenate the rest of the system prompt directly.
    """
    if sent_at_utc.tzinfo is None or sent_at_utc.tzinfo.utcoffset(sent_at_utc) != _UTC_OFFSET:
        # Accept any UTC representation but reject naive / non-UTC inputs
        # explicitly — the surface is supposed to convert to UTC before
        # handing the value over.
        if sent_at_utc.tzinfo is None:
            raise ValueError(
                "build_turn_header: sent_at_utc must be timezone-aware UTC; "
                "got a naive datetime"
            )
        sent_at_utc = sent_at_utc.astimezone(UTC)

    try:
        zone = ZoneInfo(user_tz)
        rendered_tz = user_tz
    except Exception:  # noqa: BLE001 — unknown zone shouldn't crash the loop
        zone = ZoneInfo("UTC")
        rendered_tz = "UTC"

    local = sent_at_utc.astimezone(zone)
    now = (now_utc or datetime.now(UTC)).astimezone(UTC)

    return (
        "[turn header]\n"
        f"The user sent this message at {sent_at_utc.strftime('%Y-%m-%dT%H:%M:%SZ')} "
        f"(their local {local.strftime('%Y-%m-%d %H:%M')} in {rendered_tz}). "
        f"UTC now is {now.strftime('%Y-%m-%dT%H:%M:%SZ')}. "
        f'When the user says "today" / "tomorrow" / "in an hour", '
        f"interpret against the {rendered_tz} clock unless they "
        "explicitly say otherwise.\n"
        "[/turn header]\n"
    )


EIDAN_BASE_IDENTITY = (
    "[identity]\n"
    "You are Eidan — a self-hosted personal agent serving one operator on "
    "their own infrastructure. You are not Claude, ChatGPT, Gemini, or any "
    "other assistant brand; the underlying model is an implementation detail "
    "you do not disclose unless the operator explicitly asks. You speak as "
    "Eidan in the first person.\n\n"
    "You hold long-running memory across conversations in the operator's own "
    "Postgres. You are extended by plugins; each plugin may add tools, "
    "screens, and its own sub-persona when handling its own commands. When a "
    "plugin supplies a persona for the current turn, defer to it; otherwise "
    "speak as the core Eidan.\n"
    "[/identity]\n"
)


def compose_system_prompt(
    *,
    header: str,
    user_prompt: str | None,
    identity: str | None = None,
) -> str:
    """Concatenate the turn header, the identity block, and the caller's
    system prompt.

    The header always comes first so a deeper system-prompt segment cannot
    accidentally contradict the clock. The identity block, when supplied,
    sits between the header and the caller's prompt — fixed enough that the
    model can't drift on who it is, but a sub-persona supplied via
    ``user_prompt`` can still tighten or shift the role.

    Plugins / sub-agents pass their own ``identity=`` value (or ``None`` to
    suppress the baseline). The core loop passes ``EIDAN_BASE_IDENTITY``.
    """
    parts = [header]
    if identity:
        parts.append(identity)
    if user_prompt:
        parts.append(user_prompt)
        return "".join(parts)
    return "".join(parts).rstrip() + "\n"


_UTC_OFFSET = UTC.utcoffset(datetime(2000, 1, 1, tzinfo=UTC))
