-- eidan.* schema baseline (snapshot of the deployed schema; supersedes the Alembic history).
-- Generated by pg_dump; apply via the Node runner (../migrate.mjs).

--
-- PostgreSQL database dump
--


-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.10 (Debian 17.10-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: eidan; Type: SCHEMA; Schema: -; Owner: -
--



--
-- Name: set_updated_at(); Type: FUNCTION; Schema: eidan; Owner: -
--

CREATE FUNCTION eidan.set_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
        BEGIN
            NEW.updated_at := now();
            RETURN NEW;
        END;
        $$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: agent_context; Type: TABLE; Schema: eidan; Owner: -
--

CREATE TABLE eidan.agent_context (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    agent_slug text NOT NULL,
    display_name text NOT NULL,
    description text,
    code_defaults jsonb DEFAULT '{}'::jsonb NOT NULL,
    user_overrides jsonb DEFAULT '{}'::jsonb NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT agent_context_slug_chk CHECK ((agent_slug ~ '^[a-z0-9][a-z0-9_-]*$'::text))
);


--
-- Name: artifact_blobs; Type: TABLE; Schema: eidan; Owner: -
--

CREATE TABLE eidan.artifact_blobs (
    artifact_id uuid NOT NULL,
    data bytea NOT NULL
);


--
-- Name: artifacts; Type: TABLE; Schema: eidan; Owner: -
--

CREATE TABLE eidan.artifacts (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    conversation_id uuid,
    message_id uuid,
    kind text NOT NULL,
    mime_type text NOT NULL,
    filename text NOT NULL,
    size_bytes bigint NOT NULL,
    storage_key text NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_by text DEFAULT 'agent'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    CONSTRAINT artifacts_created_by_check CHECK ((created_by = ANY (ARRAY['user'::text, 'agent'::text])))
);


--
-- Name: auth_keypair; Type: TABLE; Schema: eidan; Owner: -
--

CREATE TABLE eidan.auth_keypair (
    id text NOT NULL,
    private_pem_enc bytea NOT NULL,
    public_pem text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: auth_magic_links; Type: TABLE; Schema: eidan; Owner: -
--

CREATE TABLE eidan.auth_magic_links (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    email text NOT NULL,
    token_hash text NOT NULL,
    code text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    consumed_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: auth_mfa_totp; Type: TABLE; Schema: eidan; Owner: -
--

CREATE TABLE eidan.auth_mfa_totp (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    secret_enc bytea NOT NULL,
    verified_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: auth_sessions; Type: TABLE; Schema: eidan; Owner: -
--

CREATE TABLE eidan.auth_sessions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    refresh_token_hash text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone,
    user_agent text,
    ip_address inet,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    last_used_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: behaviour_dlq; Type: TABLE; Schema: eidan; Owner: -
--

CREATE TABLE eidan.behaviour_dlq (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    behaviour_id text NOT NULL,
    trigger_kind text NOT NULL,
    idempotency_key text NOT NULL,
    error_class text NOT NULL,
    error_message text NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    status text DEFAULT 'pending'::text NOT NULL,
    CONSTRAINT behaviour_dlq_status_chk CHECK ((status = ANY (ARRAY['pending'::text, 'acknowledged'::text, 'resolved'::text]))),
    CONSTRAINT behaviour_dlq_trigger_kind_chk CHECK ((trigger_kind = ANY (ARRAY['cron'::text, 'schedule'::text, 'event'::text, 'webhook'::text, 'intent'::text, 'agent'::text])))
);


--
-- Name: conversations; Type: TABLE; Schema: eidan; Owner: -
--

CREATE TABLE eidan.conversations (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    title text,
    agent_id uuid,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    parent_conversation_id uuid,
    origin_message_id uuid,
    version bigint DEFAULT 1 NOT NULL,
    status text DEFAULT 'active'::text NOT NULL,
    persona text,
    contexts jsonb DEFAULT '[]'::jsonb NOT NULL,
    CONSTRAINT conversations_status_chk CHECK ((status = ANY (ARRAY['active'::text, 'archived'::text, 'pinned'::text])))
);


--
-- Name: escalations; Type: TABLE; Schema: eidan; Owner: -
--

CREATE TABLE eidan.escalations (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    conversation_id uuid,
    agent_id uuid,
    severity text NOT NULL,
    reason_class text NOT NULL,
    suggested_action text,
    evidence jsonb DEFAULT '[]'::jsonb NOT NULL,
    status text DEFAULT 'pending'::text NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    resolved_at timestamp with time zone,
    CONSTRAINT escalations_reason_chk CHECK ((reason_class = ANY (ARRAY['missing_input'::text, 'permission_denied'::text, 'external_failure'::text, 'ambiguous_intent'::text, 'over_budget'::text, 'over_capacity'::text, 'no_progress'::text, 'unrecoverable_error'::text, 'other'::text]))),
    CONSTRAINT escalations_severity_chk CHECK ((severity = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text]))),
    CONSTRAINT escalations_status_chk CHECK ((status = ANY (ARRAY['pending'::text, 'acknowledged'::text, 'resolved'::text])))
);


--
-- Name: events; Type: TABLE; Schema: eidan; Owner: -
--

CREATE TABLE eidan.events (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    type text NOT NULL,
    title text NOT NULL,
    body text,
    due_at timestamp with time zone,
    occurred_at timestamp with time zone,
    duration_s integer,
    status text DEFAULT 'pending'::text NOT NULL,
    recurrence text,
    external_ref text,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    CONSTRAINT events_status_chk CHECK ((status = ANY (ARRAY['pending'::text, 'in_progress'::text, 'done'::text, 'cancelled'::text, 'missed'::text]))),
    CONSTRAINT events_time_chk CHECK (((due_at IS NOT NULL) OR (occurred_at IS NOT NULL)))
);


--
-- Name: jobs; Type: TABLE; Schema: eidan; Owner: -
--

CREATE TABLE eidan.jobs (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    kind text NOT NULL,
    goal text NOT NULL,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    surface text,
    user_id uuid,
    status text DEFAULT 'queued'::text NOT NULL,
    claimed_by text,
    claimed_at timestamp with time zone,
    result jsonb,
    error text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT jobs_status_check CHECK ((status = ANY (ARRAY['queued'::text, 'claimed'::text, 'running'::text, 'done'::text, 'failed'::text, 'cancelled'::text])))
);


--
-- Name: knowledge; Type: TABLE; Schema: eidan; Owner: -
--

CREATE TABLE eidan.knowledge (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    skill text NOT NULL,
    title text NOT NULL,
    body text NOT NULL,
    source text,
    source_type text,
    body_tsv tsvector GENERATED ALWAYS AS (to_tsvector('english'::regconfig, ((COALESCE(title, ''::text) || ' '::text) || COALESCE(body, ''::text)))) STORED,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    slug text,
    CONSTRAINT knowledge_slug_chk CHECK (((slug IS NULL) OR (slug ~ '^[a-z0-9][a-z0-9_-]*(/[a-z0-9][a-z0-9_-]*)?$'::text))),
    CONSTRAINT knowledge_source_type_chk CHECK (((source_type IS NULL) OR (source_type = ANY (ARRAY['url'::text, 'file'::text, 'chat'::text, 'manual'::text, 'imported'::text]))))
);


--
-- Name: knowledge_links; Type: TABLE; Schema: eidan; Owner: -
--

CREATE TABLE eidan.knowledge_links (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    from_knowledge_id uuid NOT NULL,
    to_knowledge_id uuid,
    to_slug text NOT NULL,
    link_type text NOT NULL,
    position_offset integer NOT NULL,
    surrounding_context text NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT knowledge_links_link_type_chk CHECK ((link_type = ANY (ARRAY['wikilink'::text, 'markdown'::text]))),
    CONSTRAINT knowledge_links_offset_chk CHECK ((position_offset >= 0))
);


--
-- Name: llm_calls; Type: TABLE; Schema: eidan; Owner: -
--

CREATE TABLE eidan.llm_calls (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    conversation_id uuid,
    message_id uuid,
    agent_id uuid,
    role text NOT NULL,
    provider text NOT NULL,
    model text NOT NULL,
    input_tokens integer DEFAULT 0 NOT NULL,
    output_tokens integer DEFAULT 0 NOT NULL,
    cache_read_tokens integer DEFAULT 0 NOT NULL,
    cache_creation_tokens integer DEFAULT 0 NOT NULL,
    cost_usd numeric(12,6) DEFAULT 0 NOT NULL,
    latency_ms integer,
    error text,
    error_type text,
    started_at timestamp with time zone NOT NULL,
    finished_at timestamp with time zone,
    request_id text,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT llm_calls_role_chk CHECK ((role = ANY (ARRAY['primary'::text, 'scope_classifier'::text, 'sizer'::text, 'intent_classifier'::text, 'behaviour_classifier'::text, 'critic'::text, 'failure_classifier'::text, 'subagent'::text, 'summariser'::text, 'tool_synthesis'::text, 'plugin_tool'::text, 'embed'::text, 'other'::text]))),
    CONSTRAINT llm_calls_tokens_chk CHECK (((input_tokens >= 0) AND (output_tokens >= 0) AND (cache_read_tokens >= 0) AND (cache_creation_tokens >= 0)))
);


--
-- Name: messages; Type: TABLE; Schema: eidan; Owner: -
--

CREATE TABLE eidan.messages (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    conversation_id uuid NOT NULL,
    parent_message_id uuid,
    agent_id uuid,
    role text NOT NULL,
    content text,
    tool_calls jsonb DEFAULT '[]'::jsonb NOT NULL,
    tool_results jsonb DEFAULT '[]'::jsonb NOT NULL,
    provider text,
    model text,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    content_blocks jsonb DEFAULT '[]'::jsonb NOT NULL,
    trace_id text,
    seq bigint NOT NULL,
    CONSTRAINT messages_role_chk CHECK ((role = ANY (ARRAY['user'::text, 'assistant'::text, 'system'::text, 'tool'::text, 'marker'::text])))
);


--
-- Name: messages_seq_seq; Type: SEQUENCE; Schema: eidan; Owner: -
--

ALTER TABLE eidan.messages ALTER COLUMN seq ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME eidan.messages_seq_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: node_capability_overrides; Type: TABLE; Schema: eidan; Owner: -
--

CREATE TABLE eidan.node_capability_overrides (
    node_id text NOT NULL,
    capability text NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: node_events; Type: TABLE; Schema: eidan; Owner: -
--

CREATE TABLE eidan.node_events (
    node_id text NOT NULL,
    seq bigint NOT NULL,
    ts timestamp with time zone DEFAULT now() NOT NULL,
    type text NOT NULL,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    conversation_id uuid
);


--
-- Name: node_heartbeats; Type: TABLE; Schema: eidan; Owner: -
--

CREATE TABLE eidan.node_heartbeats (
    node_id text NOT NULL,
    node_type text NOT NULL,
    status text DEFAULT 'online'::text NOT NULL,
    last_seen timestamp with time zone DEFAULT now() NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    plugins jsonb DEFAULT '[]'::jsonb NOT NULL,
    served_kinds jsonb DEFAULT '[]'::jsonb NOT NULL,
    CONSTRAINT node_heartbeats_node_type_check CHECK ((node_type = ANY (ARRAY['pi'::text, 'fly'::text, 'heroku'::text, 'k8s'::text, 'local'::text]))),
    CONSTRAINT node_heartbeats_status_check CHECK ((status = ANY (ARRAY['online'::text, 'offline'::text, 'degraded'::text])))
);


--
-- Name: notes; Type: TABLE; Schema: eidan; Owner: -
--

CREATE TABLE eidan.notes (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    agent_id uuid NOT NULL,
    conversation_id uuid,
    content text NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone
);


--
-- Name: plugin_state; Type: TABLE; Schema: eidan; Owner: -
--

CREATE TABLE eidan.plugin_state (
    name text NOT NULL,
    version text NOT NULL,
    installed_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT plugin_state_name_chk CHECK ((name ~ '^[a-z0-9][a-z0-9-]*$'::text))
);


--
-- Name: secrets_audit; Type: TABLE; Schema: eidan; Owner: -
--

CREATE TABLE eidan.secrets_audit (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid,
    scope text NOT NULL,
    key text NOT NULL,
    action text NOT NULL,
    actor text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT secrets_audit_action_check CHECK ((action = ANY (ARRAY['read'::text, 'write'::text, 'delete'::text, 'denied'::text])))
);


--
-- Name: secrets_vault; Type: TABLE; Schema: eidan; Owner: -
--

CREATE TABLE eidan.secrets_vault (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    scope text NOT NULL,
    key text NOT NULL,
    value_enc bytea NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    user_id uuid,
    expires_at timestamp with time zone
);


--
-- Name: user_context; Type: TABLE; Schema: eidan; Owner: -
--

CREATE TABLE eidan.user_context (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    category text NOT NULL,
    key text NOT NULL,
    value jsonb NOT NULL,
    source text,
    confidence real,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    CONSTRAINT user_context_category_chk CHECK ((category = ANY (ARRAY['identity'::text, 'goals'::text, 'constraints'::text, 'preferences'::text, 'projects'::text]))),
    CONSTRAINT user_context_confidence_chk CHECK (((confidence IS NULL) OR ((confidence >= (0.0)::double precision) AND (confidence <= (1.0)::double precision))))
);


--
-- Name: users; Type: TABLE; Schema: eidan; Owner: -
--

CREATE TABLE eidan.users (
    id uuid NOT NULL,
    email text,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    kind text DEFAULT 'human'::text NOT NULL,
    CONSTRAINT users_human_email_required CHECK (((kind <> 'human'::text) OR (email IS NOT NULL))),
    CONSTRAINT users_kind_chk CHECK ((kind = ANY (ARRAY['human'::text, 'agent'::text, 'system'::text])))
);


--
-- Name: agent_context agent_context_pkey; Type: CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.agent_context
    ADD CONSTRAINT agent_context_pkey PRIMARY KEY (id);


--
-- Name: agent_context agent_context_user_slug_uq; Type: CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.agent_context
    ADD CONSTRAINT agent_context_user_slug_uq UNIQUE (user_id, agent_slug);


--
-- Name: artifact_blobs artifact_blobs_pkey; Type: CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.artifact_blobs
    ADD CONSTRAINT artifact_blobs_pkey PRIMARY KEY (artifact_id);


--
-- Name: artifacts artifacts_pkey; Type: CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.artifacts
    ADD CONSTRAINT artifacts_pkey PRIMARY KEY (id);


--
-- Name: auth_keypair auth_keypair_pkey; Type: CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.auth_keypair
    ADD CONSTRAINT auth_keypair_pkey PRIMARY KEY (id);


--
-- Name: auth_magic_links auth_magic_links_pkey; Type: CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.auth_magic_links
    ADD CONSTRAINT auth_magic_links_pkey PRIMARY KEY (id);


--
-- Name: auth_magic_links auth_magic_links_token_hash_key; Type: CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.auth_magic_links
    ADD CONSTRAINT auth_magic_links_token_hash_key UNIQUE (token_hash);


--
-- Name: auth_mfa_totp auth_mfa_totp_pkey; Type: CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.auth_mfa_totp
    ADD CONSTRAINT auth_mfa_totp_pkey PRIMARY KEY (id);


--
-- Name: auth_mfa_totp auth_mfa_totp_user_id_key; Type: CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.auth_mfa_totp
    ADD CONSTRAINT auth_mfa_totp_user_id_key UNIQUE (user_id);


--
-- Name: auth_sessions auth_sessions_pkey; Type: CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.auth_sessions
    ADD CONSTRAINT auth_sessions_pkey PRIMARY KEY (id);


--
-- Name: auth_sessions auth_sessions_refresh_token_hash_key; Type: CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.auth_sessions
    ADD CONSTRAINT auth_sessions_refresh_token_hash_key UNIQUE (refresh_token_hash);


--
-- Name: behaviour_dlq behaviour_dlq_pkey; Type: CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.behaviour_dlq
    ADD CONSTRAINT behaviour_dlq_pkey PRIMARY KEY (id);


--
-- Name: conversations conversations_pkey; Type: CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.conversations
    ADD CONSTRAINT conversations_pkey PRIMARY KEY (id);


--
-- Name: escalations escalations_pkey; Type: CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.escalations
    ADD CONSTRAINT escalations_pkey PRIMARY KEY (id);


--
-- Name: events events_pkey; Type: CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.events
    ADD CONSTRAINT events_pkey PRIMARY KEY (id);


--
-- Name: jobs jobs_pkey; Type: CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.jobs
    ADD CONSTRAINT jobs_pkey PRIMARY KEY (id);


--
-- Name: knowledge_links knowledge_links_pkey; Type: CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.knowledge_links
    ADD CONSTRAINT knowledge_links_pkey PRIMARY KEY (id);


--
-- Name: knowledge knowledge_pkey; Type: CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.knowledge
    ADD CONSTRAINT knowledge_pkey PRIMARY KEY (id);


--
-- Name: llm_calls llm_calls_pkey; Type: CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.llm_calls
    ADD CONSTRAINT llm_calls_pkey PRIMARY KEY (id);


--
-- Name: messages messages_pkey; Type: CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.messages
    ADD CONSTRAINT messages_pkey PRIMARY KEY (id);


--
-- Name: node_capability_overrides node_capability_overrides_pkey; Type: CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.node_capability_overrides
    ADD CONSTRAINT node_capability_overrides_pkey PRIMARY KEY (node_id, capability);


--
-- Name: node_events node_events_pkey; Type: CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.node_events
    ADD CONSTRAINT node_events_pkey PRIMARY KEY (node_id, seq);


--
-- Name: node_heartbeats node_heartbeats_pkey; Type: CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.node_heartbeats
    ADD CONSTRAINT node_heartbeats_pkey PRIMARY KEY (node_id);


--
-- Name: notes notes_pkey; Type: CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.notes
    ADD CONSTRAINT notes_pkey PRIMARY KEY (id);


--
-- Name: plugin_state plugin_state_pkey; Type: CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.plugin_state
    ADD CONSTRAINT plugin_state_pkey PRIMARY KEY (name);


--
-- Name: secrets_audit secrets_audit_pkey; Type: CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.secrets_audit
    ADD CONSTRAINT secrets_audit_pkey PRIMARY KEY (id);


--
-- Name: secrets_vault secrets_vault_pkey; Type: CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.secrets_vault
    ADD CONSTRAINT secrets_vault_pkey PRIMARY KEY (id);


--
-- Name: secrets_vault secrets_vault_user_scope_key_unique; Type: CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.secrets_vault
    ADD CONSTRAINT secrets_vault_user_scope_key_unique UNIQUE NULLS NOT DISTINCT (user_id, scope, key);


--
-- Name: user_context user_context_pkey; Type: CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.user_context
    ADD CONSTRAINT user_context_pkey PRIMARY KEY (id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: idx_agent_context_user_enabled; Type: INDEX; Schema: eidan; Owner: -
--

CREATE INDEX idx_agent_context_user_enabled ON eidan.agent_context USING btree (user_id) WHERE (enabled = true);


--
-- Name: idx_artifacts_message; Type: INDEX; Schema: eidan; Owner: -
--

CREATE INDEX idx_artifacts_message ON eidan.artifacts USING btree (message_id) WHERE (deleted_at IS NULL);


--
-- Name: idx_artifacts_user_recent; Type: INDEX; Schema: eidan; Owner: -
--

CREATE INDEX idx_artifacts_user_recent ON eidan.artifacts USING btree (user_id, created_at DESC) WHERE (deleted_at IS NULL);


--
-- Name: idx_auth_magic_links_pending; Type: INDEX; Schema: eidan; Owner: -
--

CREATE INDEX idx_auth_magic_links_pending ON eidan.auth_magic_links USING btree (token_hash) WHERE (consumed_at IS NULL);


--
-- Name: idx_auth_sessions_user_active; Type: INDEX; Schema: eidan; Owner: -
--

CREATE INDEX idx_auth_sessions_user_active ON eidan.auth_sessions USING btree (user_id, expires_at DESC) WHERE (revoked_at IS NULL);


--
-- Name: idx_behaviour_dlq_by_behaviour; Type: INDEX; Schema: eidan; Owner: -
--

CREATE INDEX idx_behaviour_dlq_by_behaviour ON eidan.behaviour_dlq USING btree (behaviour_id, created_at DESC);


--
-- Name: idx_behaviour_dlq_pending; Type: INDEX; Schema: eidan; Owner: -
--

CREATE INDEX idx_behaviour_dlq_pending ON eidan.behaviour_dlq USING btree (created_at DESC) WHERE (status = 'pending'::text);


--
-- Name: idx_conversations_agent; Type: INDEX; Schema: eidan; Owner: -
--

CREATE INDEX idx_conversations_agent ON eidan.conversations USING btree (agent_id) WHERE (deleted_at IS NULL);


--
-- Name: idx_conversations_origin_message; Type: INDEX; Schema: eidan; Owner: -
--

CREATE INDEX idx_conversations_origin_message ON eidan.conversations USING btree (origin_message_id) WHERE ((origin_message_id IS NOT NULL) AND (deleted_at IS NULL));


--
-- Name: idx_conversations_parent; Type: INDEX; Schema: eidan; Owner: -
--

CREATE INDEX idx_conversations_parent ON eidan.conversations USING btree (parent_conversation_id, created_at DESC) WHERE ((parent_conversation_id IS NOT NULL) AND (deleted_at IS NULL));


--
-- Name: idx_conversations_user_recent; Type: INDEX; Schema: eidan; Owner: -
--

CREATE INDEX idx_conversations_user_recent ON eidan.conversations USING btree (user_id, created_at DESC) WHERE (deleted_at IS NULL);


--
-- Name: idx_escalations_user_pending; Type: INDEX; Schema: eidan; Owner: -
--

CREATE INDEX idx_escalations_user_pending ON eidan.escalations USING btree (user_id, created_at DESC) WHERE (status = 'pending'::text);


--
-- Name: idx_events_recurrence; Type: INDEX; Schema: eidan; Owner: -
--

CREATE INDEX idx_events_recurrence ON eidan.events USING btree (user_id) WHERE ((recurrence IS NOT NULL) AND (status = 'pending'::text) AND (deleted_at IS NULL));


--
-- Name: idx_events_user_due_pending; Type: INDEX; Schema: eidan; Owner: -
--

CREATE INDEX idx_events_user_due_pending ON eidan.events USING btree (user_id, due_at) WHERE ((status = 'pending'::text) AND (deleted_at IS NULL) AND (due_at IS NOT NULL));


--
-- Name: idx_events_user_occurred; Type: INDEX; Schema: eidan; Owner: -
--

CREATE INDEX idx_events_user_occurred ON eidan.events USING btree (user_id, occurred_at DESC) WHERE ((deleted_at IS NULL) AND (occurred_at IS NOT NULL));


--
-- Name: idx_events_user_type_due; Type: INDEX; Schema: eidan; Owner: -
--

CREATE INDEX idx_events_user_type_due ON eidan.events USING btree (user_id, type, due_at) WHERE ((deleted_at IS NULL) AND (due_at IS NOT NULL));


--
-- Name: idx_knowledge_body_tsv; Type: INDEX; Schema: eidan; Owner: -
--

CREATE INDEX idx_knowledge_body_tsv ON eidan.knowledge USING gin (body_tsv) WHERE (deleted_at IS NULL);


--
-- Name: idx_knowledge_links_from; Type: INDEX; Schema: eidan; Owner: -
--

CREATE INDEX idx_knowledge_links_from ON eidan.knowledge_links USING btree (from_knowledge_id, position_offset);


--
-- Name: idx_knowledge_links_to; Type: INDEX; Schema: eidan; Owner: -
--

CREATE INDEX idx_knowledge_links_to ON eidan.knowledge_links USING btree (to_knowledge_id) WHERE (to_knowledge_id IS NOT NULL);


--
-- Name: idx_knowledge_links_to_slug_unresolved; Type: INDEX; Schema: eidan; Owner: -
--

CREATE INDEX idx_knowledge_links_to_slug_unresolved ON eidan.knowledge_links USING btree (user_id, to_slug) WHERE (to_knowledge_id IS NULL);


--
-- Name: idx_knowledge_links_user_created; Type: INDEX; Schema: eidan; Owner: -
--

CREATE INDEX idx_knowledge_links_user_created ON eidan.knowledge_links USING btree (user_id, created_at DESC);


--
-- Name: idx_knowledge_user_skill; Type: INDEX; Schema: eidan; Owner: -
--

CREATE INDEX idx_knowledge_user_skill ON eidan.knowledge USING btree (user_id, skill) WHERE (deleted_at IS NULL);


--
-- Name: idx_llm_calls_conversation; Type: INDEX; Schema: eidan; Owner: -
--

CREATE INDEX idx_llm_calls_conversation ON eidan.llm_calls USING btree (conversation_id, created_at) WHERE (conversation_id IS NOT NULL);


--
-- Name: idx_llm_calls_errors; Type: INDEX; Schema: eidan; Owner: -
--

CREATE INDEX idx_llm_calls_errors ON eidan.llm_calls USING btree (user_id, created_at DESC) WHERE (error IS NOT NULL);


--
-- Name: idx_llm_calls_message; Type: INDEX; Schema: eidan; Owner: -
--

CREATE INDEX idx_llm_calls_message ON eidan.llm_calls USING btree (message_id) WHERE (message_id IS NOT NULL);


--
-- Name: idx_llm_calls_provider_model_created; Type: INDEX; Schema: eidan; Owner: -
--

CREATE INDEX idx_llm_calls_provider_model_created ON eidan.llm_calls USING btree (provider, model, created_at DESC);


--
-- Name: idx_llm_calls_user_created; Type: INDEX; Schema: eidan; Owner: -
--

CREATE INDEX idx_llm_calls_user_created ON eidan.llm_calls USING btree (user_id, created_at DESC);


--
-- Name: idx_messages_agent_recent; Type: INDEX; Schema: eidan; Owner: -
--

CREATE INDEX idx_messages_agent_recent ON eidan.messages USING btree (agent_id, created_at DESC) WHERE ((agent_id IS NOT NULL) AND (deleted_at IS NULL));


--
-- Name: idx_messages_conversation_created; Type: INDEX; Schema: eidan; Owner: -
--

CREATE INDEX idx_messages_conversation_created ON eidan.messages USING btree (conversation_id, created_at) WHERE (deleted_at IS NULL);


--
-- Name: idx_messages_parent; Type: INDEX; Schema: eidan; Owner: -
--

CREATE INDEX idx_messages_parent ON eidan.messages USING btree (parent_message_id) WHERE (parent_message_id IS NOT NULL);


--
-- Name: idx_messages_user_recent; Type: INDEX; Schema: eidan; Owner: -
--

CREATE INDEX idx_messages_user_recent ON eidan.messages USING btree (user_id, created_at DESC) WHERE (deleted_at IS NULL);


--
-- Name: idx_notes_agent_recent; Type: INDEX; Schema: eidan; Owner: -
--

CREATE INDEX idx_notes_agent_recent ON eidan.notes USING btree (agent_id, created_at DESC) WHERE (deleted_at IS NULL);


--
-- Name: idx_notes_conversation; Type: INDEX; Schema: eidan; Owner: -
--

CREATE INDEX idx_notes_conversation ON eidan.notes USING btree (conversation_id, created_at) WHERE ((conversation_id IS NOT NULL) AND (deleted_at IS NULL));


--
-- Name: idx_notes_user_recent; Type: INDEX; Schema: eidan; Owner: -
--

CREATE INDEX idx_notes_user_recent ON eidan.notes USING btree (user_id, created_at DESC) WHERE (deleted_at IS NULL);


--
-- Name: idx_user_context_user_category; Type: INDEX; Schema: eidan; Owner: -
--

CREATE INDEX idx_user_context_user_category ON eidan.user_context USING btree (user_id, category) WHERE (deleted_at IS NULL);


--
-- Name: jobs_inflight_node_idx; Type: INDEX; Schema: eidan; Owner: -
--

CREATE INDEX jobs_inflight_node_idx ON eidan.jobs USING btree (claimed_by, claimed_at) WHERE (status = ANY (ARRAY['claimed'::text, 'running'::text]));


--
-- Name: jobs_queued_kind_idx; Type: INDEX; Schema: eidan; Owner: -
--

CREATE INDEX jobs_queued_kind_idx ON eidan.jobs USING btree (kind, created_at) WHERE (status = 'queued'::text);


--
-- Name: node_events_node_conversation_seq_idx; Type: INDEX; Schema: eidan; Owner: -
--

CREATE INDEX node_events_node_conversation_seq_idx ON eidan.node_events USING btree (node_id, conversation_id, seq) WHERE (conversation_id IS NOT NULL);


--
-- Name: node_events_node_seq_idx; Type: INDEX; Schema: eidan; Owner: -
--

CREATE INDEX node_events_node_seq_idx ON eidan.node_events USING btree (node_id, seq DESC);


--
-- Name: node_events_node_ts_idx; Type: INDEX; Schema: eidan; Owner: -
--

CREATE INDEX node_events_node_ts_idx ON eidan.node_events USING btree (node_id, ts DESC);


--
-- Name: node_heartbeats_last_seen_idx; Type: INDEX; Schema: eidan; Owner: -
--

CREATE INDEX node_heartbeats_last_seen_idx ON eidan.node_heartbeats USING btree (last_seen DESC);


--
-- Name: secrets_audit_created_idx; Type: INDEX; Schema: eidan; Owner: -
--

CREATE INDEX secrets_audit_created_idx ON eidan.secrets_audit USING btree (created_at DESC);


--
-- Name: secrets_vault_expires_at_idx; Type: INDEX; Schema: eidan; Owner: -
--

CREATE INDEX secrets_vault_expires_at_idx ON eidan.secrets_vault USING btree (expires_at) WHERE (expires_at IS NOT NULL);


--
-- Name: uq_knowledge_user_skill_title; Type: INDEX; Schema: eidan; Owner: -
--

CREATE UNIQUE INDEX uq_knowledge_user_skill_title ON eidan.knowledge USING btree (user_id, skill, title) WHERE (deleted_at IS NULL);


--
-- Name: uq_knowledge_user_slug; Type: INDEX; Schema: eidan; Owner: -
--

CREATE UNIQUE INDEX uq_knowledge_user_slug ON eidan.knowledge USING btree (user_id, slug) WHERE ((deleted_at IS NULL) AND (slug IS NOT NULL));


--
-- Name: uq_user_context_user_cat_key; Type: INDEX; Schema: eidan; Owner: -
--

CREATE UNIQUE INDEX uq_user_context_user_cat_key ON eidan.user_context USING btree (user_id, category, key) WHERE (deleted_at IS NULL);


--
-- Name: agent_context trg_agent_context_updated_at; Type: TRIGGER; Schema: eidan; Owner: -
--

CREATE TRIGGER trg_agent_context_updated_at BEFORE UPDATE ON eidan.agent_context FOR EACH ROW EXECUTE FUNCTION eidan.set_updated_at();


--
-- Name: artifacts trg_artifacts_updated_at; Type: TRIGGER; Schema: eidan; Owner: -
--

CREATE TRIGGER trg_artifacts_updated_at BEFORE UPDATE ON eidan.artifacts FOR EACH ROW EXECUTE FUNCTION eidan.set_updated_at();


--
-- Name: conversations trg_conversations_updated_at; Type: TRIGGER; Schema: eidan; Owner: -
--

CREATE TRIGGER trg_conversations_updated_at BEFORE UPDATE ON eidan.conversations FOR EACH ROW EXECUTE FUNCTION eidan.set_updated_at();


--
-- Name: events trg_events_updated_at; Type: TRIGGER; Schema: eidan; Owner: -
--

CREATE TRIGGER trg_events_updated_at BEFORE UPDATE ON eidan.events FOR EACH ROW EXECUTE FUNCTION eidan.set_updated_at();


--
-- Name: jobs trg_jobs_updated_at; Type: TRIGGER; Schema: eidan; Owner: -
--

CREATE TRIGGER trg_jobs_updated_at BEFORE UPDATE ON eidan.jobs FOR EACH ROW EXECUTE FUNCTION eidan.set_updated_at();


--
-- Name: knowledge trg_knowledge_updated_at; Type: TRIGGER; Schema: eidan; Owner: -
--

CREATE TRIGGER trg_knowledge_updated_at BEFORE UPDATE ON eidan.knowledge FOR EACH ROW EXECUTE FUNCTION eidan.set_updated_at();


--
-- Name: node_capability_overrides trg_node_capability_overrides_updated_at; Type: TRIGGER; Schema: eidan; Owner: -
--

CREATE TRIGGER trg_node_capability_overrides_updated_at BEFORE UPDATE ON eidan.node_capability_overrides FOR EACH ROW EXECUTE FUNCTION eidan.set_updated_at();


--
-- Name: node_heartbeats trg_node_heartbeats_updated_at; Type: TRIGGER; Schema: eidan; Owner: -
--

CREATE TRIGGER trg_node_heartbeats_updated_at BEFORE UPDATE ON eidan.node_heartbeats FOR EACH ROW EXECUTE FUNCTION eidan.set_updated_at();


--
-- Name: notes trg_notes_updated_at; Type: TRIGGER; Schema: eidan; Owner: -
--

CREATE TRIGGER trg_notes_updated_at BEFORE UPDATE ON eidan.notes FOR EACH ROW EXECUTE FUNCTION eidan.set_updated_at();


--
-- Name: plugin_state trg_plugin_state_updated_at; Type: TRIGGER; Schema: eidan; Owner: -
--

CREATE TRIGGER trg_plugin_state_updated_at BEFORE UPDATE ON eidan.plugin_state FOR EACH ROW EXECUTE FUNCTION eidan.set_updated_at();


--
-- Name: secrets_vault trg_secrets_vault_updated_at; Type: TRIGGER; Schema: eidan; Owner: -
--

CREATE TRIGGER trg_secrets_vault_updated_at BEFORE UPDATE ON eidan.secrets_vault FOR EACH ROW EXECUTE FUNCTION eidan.set_updated_at();


--
-- Name: user_context trg_user_context_updated_at; Type: TRIGGER; Schema: eidan; Owner: -
--

CREATE TRIGGER trg_user_context_updated_at BEFORE UPDATE ON eidan.user_context FOR EACH ROW EXECUTE FUNCTION eidan.set_updated_at();


--
-- Name: users trg_users_updated_at; Type: TRIGGER; Schema: eidan; Owner: -
--

CREATE TRIGGER trg_users_updated_at BEFORE UPDATE ON eidan.users FOR EACH ROW EXECUTE FUNCTION eidan.set_updated_at();


--
-- Name: agent_context agent_context_user_id_fkey; Type: FK CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.agent_context
    ADD CONSTRAINT agent_context_user_id_fkey FOREIGN KEY (user_id) REFERENCES eidan.users(id) ON DELETE CASCADE;


--
-- Name: artifact_blobs artifact_blobs_artifact_id_fkey; Type: FK CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.artifact_blobs
    ADD CONSTRAINT artifact_blobs_artifact_id_fkey FOREIGN KEY (artifact_id) REFERENCES eidan.artifacts(id) ON DELETE CASCADE;


--
-- Name: artifacts artifacts_conversation_id_fkey; Type: FK CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.artifacts
    ADD CONSTRAINT artifacts_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES eidan.conversations(id) ON DELETE SET NULL;


--
-- Name: artifacts artifacts_message_id_fkey; Type: FK CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.artifacts
    ADD CONSTRAINT artifacts_message_id_fkey FOREIGN KEY (message_id) REFERENCES eidan.messages(id) ON DELETE CASCADE;


--
-- Name: artifacts artifacts_user_id_fkey; Type: FK CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.artifacts
    ADD CONSTRAINT artifacts_user_id_fkey FOREIGN KEY (user_id) REFERENCES eidan.users(id) ON DELETE CASCADE;


--
-- Name: auth_mfa_totp auth_mfa_totp_user_id_fkey; Type: FK CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.auth_mfa_totp
    ADD CONSTRAINT auth_mfa_totp_user_id_fkey FOREIGN KEY (user_id) REFERENCES eidan.users(id) ON DELETE CASCADE;


--
-- Name: auth_sessions auth_sessions_user_id_fkey; Type: FK CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.auth_sessions
    ADD CONSTRAINT auth_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES eidan.users(id) ON DELETE CASCADE;


--
-- Name: conversations conversations_agent_id_fkey; Type: FK CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.conversations
    ADD CONSTRAINT conversations_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES eidan.agent_context(id) ON DELETE SET NULL;


--
-- Name: conversations conversations_origin_message_id_fkey; Type: FK CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.conversations
    ADD CONSTRAINT conversations_origin_message_id_fkey FOREIGN KEY (origin_message_id) REFERENCES eidan.messages(id) ON DELETE SET NULL;


--
-- Name: conversations conversations_parent_conversation_id_fkey; Type: FK CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.conversations
    ADD CONSTRAINT conversations_parent_conversation_id_fkey FOREIGN KEY (parent_conversation_id) REFERENCES eidan.conversations(id) ON DELETE SET NULL;


--
-- Name: conversations conversations_user_id_fkey; Type: FK CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.conversations
    ADD CONSTRAINT conversations_user_id_fkey FOREIGN KEY (user_id) REFERENCES eidan.users(id) ON DELETE CASCADE;


--
-- Name: events events_user_id_fkey; Type: FK CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.events
    ADD CONSTRAINT events_user_id_fkey FOREIGN KEY (user_id) REFERENCES eidan.users(id) ON DELETE CASCADE;


--
-- Name: jobs jobs_user_id_fkey; Type: FK CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.jobs
    ADD CONSTRAINT jobs_user_id_fkey FOREIGN KEY (user_id) REFERENCES eidan.users(id) ON DELETE SET NULL;


--
-- Name: knowledge_links knowledge_links_from_knowledge_id_fkey; Type: FK CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.knowledge_links
    ADD CONSTRAINT knowledge_links_from_knowledge_id_fkey FOREIGN KEY (from_knowledge_id) REFERENCES eidan.knowledge(id) ON DELETE CASCADE;


--
-- Name: knowledge_links knowledge_links_to_knowledge_id_fkey; Type: FK CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.knowledge_links
    ADD CONSTRAINT knowledge_links_to_knowledge_id_fkey FOREIGN KEY (to_knowledge_id) REFERENCES eidan.knowledge(id) ON DELETE SET NULL;


--
-- Name: knowledge knowledge_user_id_fkey; Type: FK CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.knowledge
    ADD CONSTRAINT knowledge_user_id_fkey FOREIGN KEY (user_id) REFERENCES eidan.users(id) ON DELETE CASCADE;


--
-- Name: llm_calls llm_calls_agent_id_fkey; Type: FK CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.llm_calls
    ADD CONSTRAINT llm_calls_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES eidan.agent_context(id) ON DELETE SET NULL;


--
-- Name: llm_calls llm_calls_conversation_id_fkey; Type: FK CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.llm_calls
    ADD CONSTRAINT llm_calls_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES eidan.conversations(id) ON DELETE SET NULL;


--
-- Name: llm_calls llm_calls_message_id_fkey; Type: FK CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.llm_calls
    ADD CONSTRAINT llm_calls_message_id_fkey FOREIGN KEY (message_id) REFERENCES eidan.messages(id) ON DELETE SET NULL;


--
-- Name: llm_calls llm_calls_user_id_fkey; Type: FK CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.llm_calls
    ADD CONSTRAINT llm_calls_user_id_fkey FOREIGN KEY (user_id) REFERENCES eidan.users(id) ON DELETE CASCADE;


--
-- Name: messages messages_agent_id_fkey; Type: FK CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.messages
    ADD CONSTRAINT messages_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES eidan.agent_context(id) ON DELETE SET NULL;


--
-- Name: messages messages_conversation_id_fkey; Type: FK CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.messages
    ADD CONSTRAINT messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES eidan.conversations(id) ON DELETE CASCADE;


--
-- Name: messages messages_parent_message_id_fkey; Type: FK CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.messages
    ADD CONSTRAINT messages_parent_message_id_fkey FOREIGN KEY (parent_message_id) REFERENCES eidan.messages(id) ON DELETE SET NULL;


--
-- Name: messages messages_user_id_fkey; Type: FK CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.messages
    ADD CONSTRAINT messages_user_id_fkey FOREIGN KEY (user_id) REFERENCES eidan.users(id) ON DELETE CASCADE;


--
-- Name: node_events node_events_node_id_fkey; Type: FK CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.node_events
    ADD CONSTRAINT node_events_node_id_fkey FOREIGN KEY (node_id) REFERENCES eidan.node_heartbeats(node_id) ON DELETE CASCADE;


--
-- Name: notes notes_agent_id_fkey; Type: FK CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.notes
    ADD CONSTRAINT notes_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES eidan.agent_context(id) ON DELETE CASCADE;


--
-- Name: notes notes_conversation_id_fkey; Type: FK CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.notes
    ADD CONSTRAINT notes_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES eidan.conversations(id) ON DELETE SET NULL;


--
-- Name: notes notes_user_id_fkey; Type: FK CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.notes
    ADD CONSTRAINT notes_user_id_fkey FOREIGN KEY (user_id) REFERENCES eidan.users(id) ON DELETE CASCADE;


--
-- Name: secrets_vault secrets_vault_user_id_fkey; Type: FK CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.secrets_vault
    ADD CONSTRAINT secrets_vault_user_id_fkey FOREIGN KEY (user_id) REFERENCES eidan.users(id) ON DELETE CASCADE;


--
-- Name: user_context user_context_user_id_fkey; Type: FK CONSTRAINT; Schema: eidan; Owner: -
--

ALTER TABLE ONLY eidan.user_context
    ADD CONSTRAINT user_context_user_id_fkey FOREIGN KEY (user_id) REFERENCES eidan.users(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--


