"""Manifest loader + validator — `docs/001 §1`.

Parses ``plugins/<name>/plugin.yaml`` with PyYAML and validates the
resulting dict against the JSON Schema authored in
``packages/schemas/schemas/core/plugin/PluginManifest.schema.json``.

The JSON Schema is the source of truth (`docs/004 §1`). Validation
runs against the generated Pydantic v2 model in
:mod:`eidan_schemas.generated.core.plugin.PluginManifest_schema`,
which is regenerated by ``pnpm schemas:gen`` and committed; CI fails
on any drift.

Failures raise :class:`MalformedManifest` with a single human
readable message that points at the failing field. The loader
(separate issue) treats this as a fatal load error per `docs/001
§1` ("plugins that fail validation are rejected, not partially
loaded").
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml
from eidan_schemas.generated.core.plugin.PluginManifest_schema import (
    PluginManifest as PluginManifestModel,
)
from pydantic import ValidationError


class MalformedManifest(Exception):
    """Raised when ``plugin.yaml`` is missing, unparsable, or invalid.

    The first argument is a human-readable message that includes the
    failing field path (e.g. ``"name: field required"``) so an
    operator looking at install logs can fix the manifest without
    reading the schema. The ``path`` attribute carries the same
    field as a tuple for programmatic callers (tests, the admin UI).
    """

    def __init__(self, message: str, *, path: tuple[str | int, ...] = ()) -> None:
        super().__init__(message)
        self.path = path


def _format_loc(loc: tuple[Any, ...]) -> str:
    """Format a Pydantic ``ValidationError`` loc tuple as ``a.b[0].c``."""
    parts: list[str] = []
    for item in loc:
        if isinstance(item, int):
            parts.append(f"[{item}]")
        else:
            parts.append(f".{item}" if parts else str(item))
    return "".join(parts) or "<root>"


def load_manifest(plugin_dir: Path) -> PluginManifestModel:
    """Load and validate ``plugin_dir / "plugin.yaml"``.

    Returns the parsed :class:`PluginManifestModel` on success. Raises
    :class:`MalformedManifest` with a clear field path on any
    failure — missing file, YAML parse error, schema violation, or
    the directory-name / ``name`` mismatch from `docs/001 §1.2`.
    """
    manifest_path = plugin_dir / "plugin.yaml"
    if not manifest_path.is_file():
        raise MalformedManifest(
            f"plugin.yaml not found at {manifest_path}",
            path=("plugin.yaml",),
        )

    try:
        raw_text = manifest_path.read_text(encoding="utf-8")
    except OSError as exc:
        raise MalformedManifest(
            f"plugin.yaml unreadable at {manifest_path}: {exc}",
            path=("plugin.yaml",),
        ) from exc

    try:
        raw: Any = yaml.safe_load(raw_text)
    except yaml.YAMLError as exc:
        raise MalformedManifest(
            f"plugin.yaml is not valid YAML: {exc}",
            path=("plugin.yaml",),
        ) from exc

    if not isinstance(raw, dict):
        raise MalformedManifest(
            "plugin.yaml top-level value must be a mapping",
            path=("plugin.yaml",),
        )

    try:
        manifest = PluginManifestModel.model_validate(raw)
    except ValidationError as exc:
        first = exc.errors()[0]
        field = _format_loc(first["loc"])
        msg = first["msg"]
        raise MalformedManifest(
            f"{field}: {msg}",
            path=tuple(first["loc"]),
        ) from exc

    # docs/001 §1.2: the plugins/<name>/ directory MUST equal the
    # manifest name. Enforce here so the loader gets a single,
    # uniform error type for every manifest problem.
    if plugin_dir.name != manifest.name:
        raise MalformedManifest(
            f"name: manifest name {manifest.name!r} does not match "
            f"directory name {plugin_dir.name!r}",
            path=("name",),
        )

    return manifest


__all__ = ["MalformedManifest", "load_manifest"]
